steps:
  - label: "update docker image"
    command: "docker pull mockserver/mockserver:maven"

  - wait

  - label: "build"
    command: "docker run -v /var/lib/buildkite-agent/builds/$BUILDKITE_AGENT_NAME/mockserver:/build -w /build/mockserver -a stdout -a stderr -e BUILDKITE_BRANCH=$BUILDKITE_BRANCH mockserver/mockserver:maven /build/mockserver/scripts/buildkite_quick_build.sh"
    
    artifact_paths:
      - "**/*.log"
